spring:
  application:
    name: api-gateway
  main:
    web-application-type: REACTIVE
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: category-routes
              uri: lb://category-service
              predicates:
                - Path=/api/category/**

server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
